version: 2
jobs:
  build:
    docker:
      - image: linuxbrew/linuxbrew
    environment:
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_VERBOSE: 1
      HOMEBREW_VERBOSE_USING_DOTS: 1
    steps:
      - run:
        name: Set up Git
        command: |
          git config --global user.name LinuxbrewTestBot
          git config --global user.email testbot@linuxbrew.sh
      - run:
        name: Set up Linuxbrew
        working_directory: /home/linuxbrew/.linuxbrew/Homebrew
        no_output_timeout: 5m
        command: |
          git pull --ff-only
      - run:
        name: Set up Linuxbrew/$CIRCLE_PROJECT_REPONAME
        no_output_timeout: 5m
        command: |
          if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
              git fetch https://github.com/Linuxbrew/$CIRCLE_PROJECT_REPONAME pull/$CIRCLE_PR_NUMBER/head
          fi
          git reset --hard $CIRCLE_SHA1
          mkdir -p /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew
          cp -a . /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/$CIRCLE_PROJECT_REPONAME
      - run:
        name: Prepare for the main test
        no_output_timeout: 5m
        command: |
          mkdir /tmp/bottles
          brew install patchelf
      - run:
        name: Main test 
        working_directory: /tmp/bottles
        no_output_timeout: 30m
        command: brew test-bot --tap=linuxbrew/xorg --bintray-org=linuxbrew --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh
      - store_artifacts:
          path: /home/linuxbrew/test-bot
          destination: bottles
      - store_test_results:
          path: /home/linuxbrew/test-bot
notify:
  webhooks:
    - url: https://p4142ivuwk.execute-api.us-west-2.amazonaws.com/prod/ci-upload
