name: Audit

on:
  pull_request:
  push:
    branches:
      - master
  
jobs:
  audit:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - uses: actions/checkout@master
      - run: pwd
      - run: ls
      - run: brew audit ./homebrew-xorg/homebrew-xorg/Formula/*.rb
