name: Audit

on:
  push:
    branches:
      - master
  
jobs:
  audit:
    runs-on: ubuntu-latest
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: brew audit Formula/*.rb
