name: Audit

on:
  push:
    branches:
      - master
  
jobs:
  audit:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
      env:
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@master
      - run: brew audit Formula/*.rb
