name: Build Bottles for Linuxbrew/Xorg

on:
  push:
    branches:
      - gh-actions
      - 'build-bottle/**'
    paths:
      - 'Formula/*.rb'

jobs:
  main:
    name: Build a Bottle

    runs-on: ubuntu-latest

    container:
      image: homebrew/brew

      env:
        HOMEBREW_DEVELOPER: 1
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_VERBOSE: 1

    steps:
      - name: Install minimal python for libxcb
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends python2.7-minimal

      - name: Set up Git
        run: |
          git config --global user.name LinuxbrewTestBot
          git config --global user.email testbot@linuxbrew.sh

      - name: Update-reset Homebrew
        run: brew update-reset

      - name: Tap Linuxbrew/xorg
        run: brew tap linuxbrew/xorg

      - name: Configure Linuxbrew/xorg 
        run: |
          git fetch origin
          git checkout ${{ github.sha }} 
        working-directory: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg

      - name: Install patchelf
        run: brew install patchelf

      - name: Main test (test-bot)
        run: brew test-bot --tap=linuxbrew/xorg --bintray-org=linuxbrew --skip-recursive-dependents --ci-upload
        env:
          HOMEBREW_BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          HOMEBREW_BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        continue-on-error: true
