name: Build and upload bottles

on:
  pull_request:
    paths:
      - 'Formula/*.rb'
      - 'Patches/*'
      - '.github/workflows/*.yml'

jobs:
  build-bottle:
    name: Build a bottle
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    env:
      HOMEBREW_CACHE: /home/linuxbrew/.cache/Homebrew
      HOMEBREW_TEMP: /tmp
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_VERBOSE: 1
    steps:
      - name: Set up SSH keys and basic Git information
        uses: Homebrew/actions/git-ssh@master
        with:
          git_user: LinuxbrewTestBot
          git_email: testbot@linuxbrew.sh
          key: ${{ secrets.SSH_KEY }}

      - name: Checkout tap
        uses: actions/checkout@v1

      - name: Update-reset Homebrew
        run: brew update-reset

      - name: Setup tap
        run: |
          mkdir -p $(dirname $(brew --repo linuxbrew/xorg))
          ln -s "$PWD" /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg

      - name: Install patchelf
        run: brew install patchelf

      - name: Fix audit errors
        working-directory: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg
        shell: bash
        run: |
          brew audit --fix --except-cops='FormulaAuditStrict/Test' Formula/*.rb
          if [[ -n $(git diff --name-only) ]]
          then
              echo "This PR failed audit checks."
              echo "Submitting fixes back to the PR and exiting."
              git add -u
              git commit -m "Fix Homebrew coding style violations (#${{github.event.pull_request.number}})"
              git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git \
              HEAD:${{github.event.pull_request.head.ref}}
              exit 1
          else
              echo "This PR has successfully passed audit checks."
          fi

      - name: Main test (test-bot)
        id: main_test
        shell: bash
        run: |
          mkdir /bottles
          cd /bottles
          brew test-bot \
              --tap=linuxbrew/xorg \
              --bintray-org=linuxbrew \
              --skip-recursive-dependents \
          && echo ::set-output name=status::success \
          || echo ::set-output name=status::failure

          echo ::set-output name=nbottles::$(shopt -s nullglob; set -- ./*x86_64_linux.bottle*tar.gz ; echo $#)

          cd $GITHUB_WORKSPACE
          mv /bottles .
        continue-on-error: true

      - name: Upload bottles
        id: upload_bottles
        if: steps.main_test.outputs.nbottles > 0
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/bottles
          brew test-bot \
              --bintray-org=linuxbrew \
              --git-name=LinuxbrewTestBot \
              --git-email=testbot@linuxbrew.sh \
              --ci-upload \
          && echo ::set-output name=status::success \
          || echo ::set-output name=status::failure
        env:
          HOMEBREW_BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          HOMEBREW_BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}

      - name: Report back to the PR
        shell: bash
        run: |
          MESSAGE="\
          **Main test status:** ${{ steps.main_test.outputs.status }}
          **Created bottles:** ${{ steps.main_test.outputs.nbottles }}"

          if [[ "${{ steps.main_test.outputs.nbottles }}" -gt 0 ]]
          then
              MESSAGE="$MESSAGE
              **Upload status:** ${{ steps.upload_bottles.outputs.status }}"
          fi

          # Replace new line characters ($'\n') with literal '\n'
          MESSAGE="${MESSAGE//$'\n'/'\n'}"

          curl --user $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }} \
               --data '{"body": "'"$MESSAGE"'"}' \
               https://api.github.com/repos/$GITHUB_REPOSITORY/issues/${{github.event.pull_request.number}}/comments
