name: Build and upload bottles

on:
  pull_request:
    paths:
      - 'Formula/*.rb'
      - 'Patches/*'
      - '.github/workflows/*.yml'

jobs:
  build-bottle:
    name: Build a bottle
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    env:
      HOMEBREW_CACHE: /home/linuxbrew/.cache/Homebrew
      HOMEBREW_TEMP: /tmp
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_COLOR: 1
      HOMEBREW_NO_EMOJI: 1
      HOMEBREW_VERBOSE: 1
    steps:
      - name: Set up SSH keys and basic Git information
        uses: Homebrew/actions/git-ssh@master
        with:
          git_user: LinuxbrewTestBot
          git_email: testbot@linuxbrew.sh
          key: ${{ secrets.SSH_KEY }}

      - name: Update-reset Homebrew
        run: brew update-reset

      # PWD: /__w/homebrew-xorg/homebrew-xorg
      - name: Checkout tap
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup tap
        run: |
          mkdir -p $(dirname $(brew --repo ${{github.repository}}))
          cp -a "$PWD" "$(brew --repo ${{github.repository}})"

      - name: Install patchelf
        run: brew install patchelf

      - name: Configure Bundle
        run: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/bundle config --global silence_root_warning 1

      - name: Fix audit errors
        working-directory: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg
        shell: bash
        run: |
          brew audit --fix --except-cops='FormulaAuditStrict/Test' Formula/*.rb || true

          if [[ -n $(git diff --name-only) ]]
          then
              git add -u Formula/
              git commit -m "Fix Homebrew coding style violations."
              git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git \
              HEAD:${{github.event.pull_request.head.ref}}
              exit 1
          fi

      - name: Main test (test-bot)
        id: main_test
        shell: bash
        run: |
          mkdir /bottles
          cd /bottles
          brew test-bot \
              --tap=linuxbrew/xorg \
              --bintray-org=linuxbrew \
              --skip-recursive-dependents \
          && echo ::set-output name=status::success \
          || echo ::set-output name=status::failure

          echo ::set-output name=nbottles::$(shopt -s nullglob; set -- ./*x86_64_linux.bottle*tar.gz ; echo $#)

          cd $GITHUB_WORKSPACE
          mv /bottles .
        continue-on-error: true

      - name: Upload bottles
        id: upload_bottles
        if: steps.main_test.outputs.nbottles > 0
        shell: bash
        working-directory: ${{github.workspace}}/bottles
        run: |
          brew update-reset # `test-bot` fails without it
          brew test-bot \
              --bintray-org=linuxbrew \
              --git-name=LinuxbrewTestBot \
              --git-email=testbot@linuxbrew.sh \
              --ci-upload \
          && echo ::set-output name=status::success \
          || echo ::set-output name=status::failure
        env:
          HOMEBREW_BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          HOMEBREW_BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          UPSTREAM_PULL_REQUEST: ${{github.event.pull_request.number}}
          HOMEBREW_CURL: /usr/bin/curl

      - name: Check that corresponding tag has been pushed to LinuxbrewTestBot
        id: check_testbot
        if: steps.main_test.outputs.nbottles > 0
        shell: bash
        run: |
          /usr/bin/curl --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
               --get --fail \
               https://api.github.com/repos/LinuxbrewTestBot/homebrew-xorg/git/ref/tags/pr-${{github.event.pull_request.number}} \
               &>/dev/null \
          && echo ::set-output name=status::yes \
          || echo ::set-output name=status::no

      - name: Report results back to the PR
        shell: bash
        run: |
          MESSAGE="\
          | Report | Status |
          | :---- | :----: |
          | **Main test (\`test-bot\`)** | ${{ steps.main_test.outputs.status }} |
          | **Bottles built** | ${{ steps.main_test.outputs.nbottles }} |"

          if [[ ${{ steps.main_test.outputs.nbottles }} -gt 0 ]]
          then
          MESSAGE="$MESSAGE
          | **Bottle upload status (\`test-bot --ci-upload\`)** | ${{ steps.upload_bottles.outputs.status }} |
          | **Tag pushed to LinuxbrewTestBot** | ${{ steps.check_testbot.outputs.status }} |"
          fi

          # Replace new line characters ($'\n') with literal '\n'
          MESSAGE="${MESSAGE//$'\n'/'\n'}"

          /usr/bin/curl --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
               --data '{"body": "'"$MESSAGE"'"}' \
               https://api.github.com/repos/$GITHUB_REPOSITORY/issues/${{github.event.pull_request.number}}/comments
