name: Build bottles from 'brew request-bottle' trigger.

on: repository_dispatch

jobs:
  bottling:
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      HOMEBREW_PATCHELF_RB: 1
      HOMEBREW_GIT_NAME: BrewTestBot
      HOMEBREW_GIT_EMAIL: 'homebrew-test-bot@lists.sfconservancy.org'
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
        # Printing these details should always be the first step listed.
      - name: ${{github.event.client_payload.formula}}
        id: print_details
        run: |
          echo formula=${{github.event.client_payload.formula}}
          echo sender=${{github.event.sender.login}}
          echo name=${{github.event.client_payload.name}}
          echo ignore-errors=${{github.event.client_payload.ignore_errors}}
          echo issue=${{github.event.client_payload.issue}}
          echo "::set-output name=repo::$(brew --repo ${{github.repository}})"

      - name: Setup git
        uses: Homebrew/actions/git-user-config@master

      - name: Install xvfb
        run: |
          apt-get update
          apt-get install --no-install-recommends -y xvfb

      - name: Update Homebrew/brew
        run: brew update-reset $(brew --repo)

      - name: Checkout tap
        uses: actions/checkout@v2

      - name: Setup tap
        run: |
          mkdir -p $(dirname $(brew --repo $GITHUB_REPOSITORY))
          ln -s $GITHUB_WORKSPACE $(brew --repo $GITHUB_REPOSITORY)

      - name: Perform local system setup check
        run: brew test-bot --only-setup

      - name: Build bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DISPLAY: ":0"
        run: |
          mkdir ~/bottles
          cd ~/bottles
          xvfb-run -s "-ac" \
          brew test-bot \
            --only-formulae \
            --tap=linuxbrew/xorg \
            --skip-recursive-dependents \
            --bintray-org=linuxbrew \
            --keep-old \
            ${{github.event.client_payload.formula}}

      - name: Output brew test-bot --only-formulae failures
        if: always()
        run: |
          cat ~/bottles/steps_output.txt
          rm ~/bottles/steps_output.txt

      - name: Copy bottles
        if: always()
        run: |
          cp -a ~/bottles $GITHUB_WORKSPACE

      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: bottles

      - name: Upload bottles to Bintray
        env:
          HOMEBREW_BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          HOMEBREW_BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
        if: success() || github.event.client_payload.ignore_errors
        run: |
          cd ~/bottles
          brew update-reset $(brew --repo ${{github.repository}})
          brew pr-upload \
            --bintray-org=linuxbrew \
            --keep-old \
            --verbose \
            --debug

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        if: success() || github.event.client_payload.ignore_errors
        with:
          directory: ${{ steps.print_details.outputs.repo }}
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}

      - name: Post comment on failure
        if: ${{!success() && github.event.client_payload.issue > 0}}
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          issue: ${{github.event.client_payload.issue}}
          body: ':warning: @${{github.actor}} bottle request for ${{github.event.client_payload.formula}} [failed](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}).'
          bot_body: ':warning: Bottle request for ${{github.event.client_payload.formula}} [failed](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}).'
          bot: BrewTestBot
