name: GitHub Actions CI

on:
  push:
    branches: master
  pull_request: []

jobs:
  tap_syntax:
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
      env:
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Update Homebrew/brew
        run: brew update-reset $(brew --repo)

      - name: Checkout tap
        uses: actions/checkout@v2

      - name: Setup tap
        run: |
          mkdir -p $(dirname $(brew --repo $GITHUB_REPOSITORY))
          ln -s $GITHUB_WORKSPACE $(brew --repo $GITHUB_REPOSITORY)

      - name: Check tap syntax
        run: brew test-bot --only-tap-syntax

  tests:
    needs: tap_syntax
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
      env:
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Install xvfb
        run: |
          apt-get update
          apt-get install --no-install-recommends -y xvfb

      - name: Update Homebrew/brew
        run: brew update-reset $(brew --repo)

      - name: Checkout tap
        uses: actions/checkout@v2

      - name: Setup tap
        run: |
          mkdir -p $(dirname $(brew --repo $GITHUB_REPOSITORY))
          ln -s $GITHUB_WORKSPACE $(brew --repo $GITHUB_REPOSITORY)

      - name: Perform local system setup check
        run: brew test-bot --only-setup

      - name: Run brew test-bot --only-formulae
        env:
          DISPLAY: ":0"
        run: |
          mkdir ~/bottles
          cd ~/bottles
          xvfb-run -s "-ac" \
          brew test-bot \
            --only-formulae \
            --tap=linuxbrew/xorg \
            --bintray-org=linuxbrew \
            --skip-recursive-dependents

      - name: Output brew test-bot --only-formulae failures
        if: always()
        run: |
          cat ~/bottles/steps_output.txt
          rm ~/bottles/steps_output.txt

      - name: Count bottles
        id: bottles
        if: always()
        run: |
          cd ~/bottles
          count=$(ls *.json | wc -l | xargs echo -n)
          echo "$count bottles"
          echo "::set-output name=count::$count"

      - name: Move bottles
        if: always() && steps.bottles.outputs.count > 0
        run: mv ~/bottles $GITHUB_WORKSPACE

      - name: Upload bottles
        if: always() && steps.bottles.outputs.count > 0
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: bottles
